# Manually-triggered
# Build MSVC Project
# Run with Valgrind

name: Cross-Platform Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-lin:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind cmake

    - name: Build project
      run: cmake . && make

    - name: Run Valgrind
      run: valgrind --leak-check=full --show-leak-kinds=all --undef-value-errors=yes --track-origins=yes build/PMS
  
  build-win:
    name: Build Windows
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Release, Debug]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} .
