name: Build and Test

on:
  push:
    branches:
      - main
      - dev

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build project
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}}
  
  test:
    runs-on: Ubuntu
    - name: Install Valgrind
      run: sudo apt install valgrind

    - name: Run Valgrind
      run: valgrind --leak-check=full ./Planar-Multibody-Simulator.exe
      working-directory: path/to/your/project
